services:
  - type: web
    name: hardy-api
    env: java
    plan: free
    buildCommand: "echo no build needed"
    startCommand: "java -jar post.hardy-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
